### ISSUE TITLE
Adicionar o consumo de gás e água no painel de energia

### ISSUE THREAD

**Issue by aantonelloborges** [rpr1972/rinnai2mqtt#2]
Mestre, não estou conseguindo adicionar as entidades "sensor.water_heater_last_water_usage" e "sensor.water_heater_last_gas_usage" no painel de controle de consumos de energia do Home Assistant.

Consegue verificar para nós?

Talvez o link abaixo ajude: https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

**Comment by rpr1972** [comment]
Buenas!

Os sensores de água e gás já tem o `device_class` específico ("water" e "gas", respectivamente), mas não tem o `state_class` necessário pra aparecer na lista do dashboard de energia (que seria "total" ou "total_increasing"). Eles foram criados dessa forma porque não fornecem dados cumulativos, mas o consumo instantâneo registrado pelo aquecedor. Pra que seja possível fornecer essa informação de forma cumulativa via integração, seria necessário armazenar os valores coletados em um banco de dados, e isso acabaria deslocando o escopo da integração - uma vez que o HA é o responsável por coletar, armazenar e processar os dados fornecidos pelas integrações.

Analisando essa questão de uma forma mais ampla, não é apenas a integração do Rinnai que opera dessa forma: na documentação do HA, sobre como adicionar consumo de água ao dashboard de energia, constam vários métodos de captura dessa informação no registro de água que vem da rua, por exemplo, e na maior parte dos casos (senão todos eles), a informação coletada é um valor instantâneo, que também vai ter que ser processado pelo HA.

Com isso em mente, o método recomendado pra atingir o teu objetivo é usar a integração "utility meter", na seção "Helpers" das configurações do HA. Ele é o último helper da lista. Eu criei um aqui pra testar mas ele só vai  mostrar as informações no dia seguinte. Dá uma olhada no link e faz um teste aí:

[https://www.home-assistant.io/integrations/utility_meter/](url)

Conforme consta no link, é possível selecionar algumas opções, circuladas em vermelho, abaixo:


![utility_meter](https://github.com/rpr1972/rinnai2mqtt/assets/139033678/03ef78ee-1588-45db-a58d-e7f495befca8)


A opção "Meter reset cycle" pode ser definida como mensal, se preferir. Eu não tenho certeza, mas acredito que o melhor seja deixar em "no cycle" pra que o valor seja perpetuamente incrementado, ao invés de ressetar a cada início de mês. Se o valor for apenas incrementado  (sem ressetar) o dashboard de energia automaticamente calcula o valor em cada mês e ano, assim como ele faz com a energia elétrica, por exemplo. Já as outras duas opções circuladas em vermelho **devem** ser setadas, com base na descrição de cada uma delas.

Vou ficar monitorando o valor desse sensor que criei pra testes e te aconselho que faça o mesmo no teu HA pra ver se o caminho é esse mesmo.

Abraço

**Comment by aantonelloborges** [comment]
Desculpe a demora.

Você conseguiu fazer funcionar?

Eu criei o helper, conforme abaixo:
<img width="1198" alt="image" src="https://github.com/rpr1972/rinnai2mqtt/assets/24994711/f79353f8-d052-4734-ad97-75df4d96a244">

Mas quando tento aadicionar ele no painél de energia ele não é listado. Se forço o nome dele o botão de update não habilita.
<img width="1512" alt="image" src="https://github.com/rpr1972/rinnai2mqtt/assets/24994711/06426a50-5de6-4145-862e-441a0b5720a8">

**Comment by rpr1972** [comment]
Buenas!

Também não obtive sucesso com essa abordagem. Além de não aparecer no painel de energia, os valores aparentemente não são somados como deveriam. Então, dessa forma, não vai funcionar mesmo.

Existe uma maneira de criar um sensor virtual que soma os valores de um outro sensor, mas o inconveniente é que ele vai ser ressetado quando o Home Assistant for reiniciado. E aí, pra um sensor que tem valores cumulativos, não tem sentido ser ressetado de vez em quando - vai bagunçar as estatísticas.

E o pior é que pra fazer isso nessa integração, nem é uma questão de ter muito trabalho: o problema é que o aquecedor Rinnai reporta o uso de gás em kcal/min e o processo de conversão pra m3 não é nem de longe preciso. É necessário saber a temperatura interna do gás no botijão pra conseguir chegar perto de uma informação que fosse relevante... E a conversão nem sequer seria direta - teria que converter pra kilograma e depois pra m3. 

Enfim, não me parece uma informação realmente útil....

Abraço
