### ISSUE TITLE
Temperatura máxima via MQTT

### ISSUE THREAD

**Issue by aantonelloborges** [rpr1972/rinnai2mqtt#3]
Outra dúvida, há algum limite das APIs para setar a temperatura máxima em 60 graus ou você limitou no código? Pois quando tento setar para 60 graus ele seta a temperatura em 46 graus.

Minha intenção é ter um botão no painel que fica em frente a pia da cozinha para que a temperatura vá a 60 para lavar algumas coisa muito gordurosa...

![IMG_0927](https://github.com/rpr1972/rinnai2mqtt/assets/24994711/92c90635-85ea-455e-95e7-82ee00b417a5)

**Comment by rpr1972** [comment]
Sim, tem uma limitação artificial em 45 graus. A ideia era tornar a barra do termostato do Home Assistant mais "curta", de forma que, ao escolher um valor "padrão" (digamos, 38 graus), ela ficasse à cerca de 1/3 do curso total. Com o máximo de 60 graus, por exemplo, ela ficaria quase sempre na faixa dos 20% - o que, esteticamente, não me parecia muito bonito.

Além disso, eu realmente achei que ninguém usaria o aquecedor nessa temperatura pra tomar banho - a menos que quisesse ter queimaduras de 1o grau. 😄

Mas, de fato, é possível remover essa limitação pra que cada usuário possa livremente escolher a temperatura desejada. 

Vou fazer isso na próxima versão, assim que tiver um tempinho livre do trabalho.

Valeu pela dica!

Abraço

**Comment by aantonelloborges** [comment]
Haha... Muito boa a piada e e verdade... Se eu aqui em casa não implemento limites de tempo para o banho e de temperatura máxima o pessoal fica 1h com 60 graus fazendo sauna... 😂

Aqui eu limitei via automação. Vou adicionar elas no meu Git e compartilho contigo junto com o código do Dashboard se quiser usar depois.

Obrigado!
🤜🤛

(Por acaso tu faz parte do grupo do LNPBR sobre Home Assistant no Discord? https://discord.com/invite/vbStJqSBz2

Me procura la ou no LinkedIn: Angelo Antonello Borges)

**Comment by rpr1972** [comment]
Ah, isso é padrão: se não ficar em cima, o gás acaba em 1 semana, e a conta d'agua vem nas alturas... 🙄 

Mas falando sobre o limite: postei uma nova versão que remove ele e permite configurar a temperatura mínima e máxima através de mais variáveis de ambiente.  Assim fica mais configurável.

Quanto à comunidades: não faço parte não, e nem tenho redes sociais. Com isso, tenho tempo pras coisas relevantes e me incomodo MUITO menos com as milhares de ideologias existentes no mundo hoje....

Abraço

**Comment by aantonelloborges** [comment]
Pura verdade! Ponto sobre essa do Discord que é grupo controlado apenas para falar de automação. Enfim, não tem ajudado muito mas às vezes o pessoal tem umas sacadas legais como para automatizar porteiro eletrônico pra avisar no HASS...

![image](https://github.com/rpr1972/rinnai2mqtt/assets/24994711/b54e8944-13bb-477a-8d02-ebbb2b5774b4)

**Comment by aantonelloborges** [comment]
Estou tentando enviar uma SET 60 via MQTT e esta ficando em 46

service: mqtt.publish
data:
  qos: "0"
  topic: rinnai_22193138/temperature/set
  payload: "60"

Seguem logs:
<img width="635" alt="image" src="https://github.com/rpr1972/rinnai2mqtt/assets/24994711/5d089b9d-f06e-42e0-95b7-22fce7108ffa">

**Comment by rpr1972** [comment]
Me parece que pode ser uma limitação no próprio aquecedor. Tem duas coisas que você pode fazer pra testar:

1) Tenta usar o aplicativo da Rinnai e vai subindo a temperatura de 1 em 1 grau, pra ver se ele passa de 46 graus;
2) Acessa a URL do aquecedor, em [ENDERECO_IP]/inc . Vai dando refresh e acompanhando no aplicativo da Rinnai, pra ver se ele vai aumentando a temperatura.

Como a temperatura tá sendo limitada em 46 graus - o que é bem específico - pode ser as tais "faixas de temperatura". Se nenhum desses dois testes funcionar, então experimenta ir no app da Rinnai, depois clica nos 3 riscos do canto superior esquerdo e clica em "Configurações do app". A primeira opção lá é pra alterar a faixa de temperatura. Se tiver em "A", passa pra "B"  ou vice-versa. 

Depois disso, avisa aqui o que aconteceu, falou?

Abraco

**Comment by jeandconte** [comment]
Seria possível atualizar para que rode a imagem DOCKER em ambiente ARM/ARM64 ? Tentei rodar em um Raspberry PI 3B (onde também tenho o HA rodando em DOCKER) e não rodou.. depois fui ver o "OS/ARCH" está somente "linux/amd64" :(

Também percebi que o sensor de GÁS não pode ser utilizado no painel de medição de uso de gás (que fica em "ENERGIA"), talvez não esteja com o tipo correto. Seria interessante se fosse possível adicionar lá!

**Comment by rpr1972** [comment]
Indo por partes:

> Seria possível atualizar para que rode a imagem DOCKER em ambiente ARM/ARM64 ? Tentei rodar em um Raspberry PI 3B (onde também tenho o HA rodando em DOCKER) e não rodou.. depois fui ver o "OS/ARCH" está somente "linux/amd64" :(

Depende muito. Eu não tenho um RPi3 pra fazer build/testar a aplicação. Posso tentar produzir uma versão arm64, mas só vai funcionar se você tiver instalado um OS 64 bit no RPi3 - se for a versão 32-bit, não vai rolar. Me avisa qual delas pra eu poder "tentar" fazer isso.

> Também percebi que o sensor de GÁS não pode ser utilizado no painel de medição de uso de gás (que fica em "ENERGIA"), talvez não esteja com o tipo correto. Seria interessante se fosse possível adicionar lá!

Quanto à isso, acho estranho: se você não conseguiu rodar o container, como foram criados os objetos no HA? 😃 Vale lembrar que o sensor padrão, que mostra a quantidade de gás consumida na última utilização do aquecedor, não é do tipo certo pra adicionar no dashboard de energia. A partir da versão 2.0.0 foi incluído um outro sensor, que acumula o consumo de gás, e esse sensor pode ser adicionado no dashboard de energia.

Pra fazer um teste, vai em "Developer tools > Services" e procura pelo sensor que tenha a string "total_gas_usage". Se ele existir, dá uma olhada nos atributos dele. O atributo "state_class" deve ser "total_increasing". Se não for, então o sensor exibido é o errado, já que esse plugin cria o sensor com essa string e com o "state_class" correto.

Abraço

**Comment by jeandconte** [comment]
Obrigado pelo retorno!!

Como sistema host uso um Rasperry PI 3B com um Ubuntu x64.

Linux home 6.8.0-1007-raspi #7-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 24 10:21:12 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

Entendo que o OS é 64 bit, e não 32 bit!

Eu estou rodando o container em uma máquina de testes com processador x86.. apontando os variáveis para o endereço IP do raspberry (que tem o MQTT e o HA em docker), e está funcionando perfeitamente... porém gostaria de remover esse container do computador inserir diretamente no raspberry, para que eu não precise manter o PC ligado! O Rapsberry consome muito menos energia.. e é suficiente para fazer tudo que é preciso.

<img width="756" alt="example" src="https://github.com/user-attachments/assets/493bfde3-3a2b-45cc-a05b-cede5ed68112">

Quanto à opção "total_gas_usage", não encontrei ... encontrei somente um "last_gas_usage", e não possui esse atributo.

![image](https://github.com/user-attachments/assets/b7461fb2-3ecd-4007-8f10-d31911fc2c1a)

De um modo geral, todos os sensores estão funcionando muito bem:

![image](https://github.com/user-attachments/assets/e7bdec97-f782-4a48-8188-211dba768c13)

**Comment by rpr1972** [comment]
> Obrigado pelo retorno!!
> 
> Como sistema host uso um Rasperry PI 3B com um Ubuntu x64.
> 
> Linux home 6.8.0-1007-raspi #7-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 24 10:21:12 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> 
> Entendo que o OS é 64 bit, e não 32 bit!

Sim, é 64 bit e acho que dá pra fazer uma versão pra ele. Era necessário saber qual a versão, porque - de acordo com a documentação do RPi3B, ele pode rodar as duas versões e pode ter usuário que opte pela versão 32 bit.

> Eu estou rodando o container em uma máquina de testes com processador x86.. apontando os variáveis para o endereço IP do raspberry (que tem o MQTT e o HA em docker), e está funcionando perfeitamente... porém gostaria de remover esse container do computador inserir diretamente no raspberry, para que eu não precise manter o PC ligado! O Rapsberry consome muito menos energia.. e é suficiente para fazer tudo que é preciso.

De fato, se já tem tudo num RPi3, é sem sentido colocar um plugin numa máquina que não fica ligada 100% do tempo. Acredito que isso possa ser resolvido.

> 
> De um modo geral, todos os sensores estão funcionando muito bem:
> 

Pois é: nessa imagem, não mostra os dois novos sensores criados na versão 2.0.0 - o que é estranho. Você consegue postar aqui o log da aplicação? Pode ter alguma mensagem que ajude no debug. Pelo que parece, o plugin não conseguiu buscar o serial number do aparelho e isso é um problema.

Abraço

**Comment by rpr1972** [comment]
Sobre a versão para ARM64, foi movido para a issue https://github.com/rpr1972/rinnai2mqtt/issues/4#issue-2428485502.

**Comment by rpr1972** [comment]
Essa issue foi encerrada.
