### ISSUE TITLE
Versão para arm64

### ISSUE THREAD

**Issue by rpr1972** [rpr1972/rinnai2mqtt#4]
Fiz uma versão inicial para Arm64 - o tag é "arm64-latest". Experimenta e vê se roda no RPI3, por favor.

Abraço

**Comment by jeandconte** [comment]
Bom dia.

Baixei a versão arm64 e testei no raspberry 3B.. subiu sem problemas! Vou manter rodando durante essa semana para ver se se mantém estável.

Quanto ao monitoramento do uso de gás, percebi que eu estava usando a  versão 1.4.2! Agora com essa LATEST do ARM64.. o "total_gas_usage" apareceu.

Obrigado!
